app:
  env:  "development"
  consumerbroker: "first.example.com:9092"
  producerbroker: "second.example.com:9092"
  #linetoken: "sdjfnasklJBS8asdnas83rq2mSJKnadfdmGFVJGSHBd3845ulzdmnfvsd"
  
nsp:
  # nspOsIP:  "172.23.160.37"    # API gateway
  # nspIprcIP: "172.23.160.30"   # API gateway
  nspOsIP:    "thalesnsp.ion.de.alcatel-lucent.com"    # API gateway
  nspIprcIP:  "thalesnsp.ion.de.alcatel-lucent.com"   # API gateway
  username:   "admin"
  password:   "NokiaNsp1!"
  # nspOsIP:    "147.75.102.178"    # API gateway
  # nspIprcIP:  "147.75.102.178"   # API gateway
  # username:   "admin"
  # password:   "zkw3VSs6"

  proxy:   
    enable: "false"
    proxyAddress: "http://138.203.39.123:80" # API proxy Gateway
